[General]

; Show Item Card keybind. (Default: Left Shift)
; Key code list located here: https://geckwiki.com/index.php?title=IsKeyPressed
iKeybind = 42

; Item Cards will automatically appear while hovering over supported items.
bShowAlways = 0

; Toggle Item Card visibility on certain item types.
bIngestibles = 1
bAmmo = 1
bWeaponMods = 1

; Display weapon critical hit chance, critical hit damage, and required skill.
bExtraWeaponStats = 1


[Interface]

; Item Cards screen position.
fPosOffsetX = 0
fPosOffsetY = 0

; Item Cards background opacity.
fBackgroundOpacity = 70


[ModSupport]

; Item Cards will replace the B42 Inspect condition check UI element.
bB42Inspect = 1
